### ISSUE TITLE
fmt.println re-prints last progress bar

### ISSUE THREAD

**Issue by gshiftlabs-ahazelton** [gosuri/uiprogress#12]
Hello,

I'm not sure if I'm doing something wrong or it's a bug.  When I execute the code below no matter what I do the progress bar will increment to 100% then when it hits the next fmt.Println it will re-print the previous progress bar at 100%.

```
uiprogress.Start()
bar := uiprogress.AddBar(length)
bar.AppendCompleted()
bar.PrependElapsed()
for _, eachFilter := range filters.Items {
    bar.Incr()
    if something exists {
        do something
    }
}
uiprogress.Stop()
bar = nil
fmt.Println("print something")
```

**Comment by gosuri** [comment]
I suspect the time taken for processing workload is relatively fast. You might try adding a wait in the for loop. Example:

``` go
package main

import (
    "fmt"
    "time"

    "github.com/gosuri/uiprogress"
)

func main() {
    items := []string{"foo", "bar", "baz"}
    bar := uiprogress.AddBar(len(items))
    bar.AppendCompleted()
    bar.PrependElapsed()
    uiprogress.Start()
    for bar.Incr() {
        time.Sleep(time.Millisecond * 500)
    }
    uiprogress.Stop()
    bar = nil
    fmt.Println("print something")
}
```

**Comment by gshiftlabs-ahazelton** [comment]
Thanks for the quick response - unfortunately that didn't work.

**Comment by gosuri** [comment]
Would love to investigate further, could you please post your code and output if possible.

**Comment by gshiftlabs-ahazelton** [comment]
Attached - line 305 - 316 is where I'm trying to implement uiprogress and line 350 seems to be the line that's writting the second progress bar to the screen.  I'm returning out of the main function at line 366 fyi

Thanks Greg,
Andrew

**Comment by gosuri** [comment]
Your program fails with an  error - `botsifter.go:224: open config.txt: no such file or directory`. I'm unable to reproduce the error as I cannot analyze the output.

Seems like  you are running a double loop. `for bar.Incr()` will run till it increments the bar to max for each item. Your code:

```go
  for _, eachFilter := range filters.Items {
    for bar.Incr() {
      time.Sleep(time.Millisecond * 500)
    }
    if strings.Contains(eachFilter.Name, "BotSifter") == true && demoFlag == false {
      service.Management.Filters.Delete(AccountID, eachFilter.Id).Do()
    }
  }
```

Change that to:

```go
  for _, eachFilter := range filters.Items {
    if strings.Contains(eachFilter.Name, "BotSifter") == true && demoFlag == false {
      service.Management.Filters.Delete(AccountID, eachFilter.Id).Do()
    }
    bar.Incr() // just increment once per item
    time.Sleep(time.Millisecond * 500)
  }
```

**Comment by gshiftlabs-ahazelton** [comment]
That's basically what I started with minus the sleep.  I just tried this and the program still prints a second bar when the program calls the next println

**Comment by gosuri** [comment]
Can you show the me output
