### ISSUE TITLE
PrependElapsed() shows wrong data for >60s

### ISSUE THREAD

**Issue by VojtechVitek** [gosuri/uiprogress#4]
<img width="676" alt="screen shot 2015-11-19 at 3 07 40 pm" src="https://cloud.githubusercontent.com/assets/139342/11282806/509b08a8-8ecf-11e5-86ba-e84515e404a5.png">

^ third line shows `24` instead of `84s` (or `1m 24s`)

**Comment by gosuri** [comment]
Thank you. That's a bug.

**Comment by gosuri** [comment]
This should be fixed now
