### ISSUE TITLE
Add Incr

### ISSUE THREAD

**Issue by bep** [gosuri/uiprogress#5]
The current `Set(int)` for setting progress works great for the common iterator, but doesn't really work for tracking of progress of work fanned out to a lot of go routines. How about an atomic `Incr` function?

**Comment by gosuri** [comment]
That's neat! How about `Incr() error`. Error when increment reaches total.

**Comment by bep** [comment]
> How about Incr() error. Error when increment reaches total.

Yes, that makes sense.

**Comment by gosuri** [comment]
Added `Incr()`

**Comment by gosuri** [comment]
Updated Incr definition to return a boolean instead. Has a cleaner API: 

``` go
for bar.Incr() {
  time.Sleep(time.Millisecond * 10)
}
```

**Comment by bep** [comment]
The API looks good, but it isn't really atomic. But looking at the rest of `bar.go` I see that that is a slightly bigger and separate task. 

But if I were you, I would do that. This is a cool little library. I was thinking about testing it in Hugo (the static site generator). That is so blistering fast, so progress bars may be moot. But in that particular use case, there are a set of processes that are fanned out to many go routines. So for `Incr` there will be data races. 

Since `bar` has more than the simple counter as state, a `RWMutex` seems like a good fit.

**Comment by gosuri** [comment]
Ah.. forgot the "atomic" part of my atomic counter 🍻🎉.  Fixed now :)
