### ISSUE TITLE
Make the progress bar concurrent safe

### ISSUE THREAD

**Issue by bep** [gosuri/uiprogress#6]
The API looks good, the implementation will experience data races when used to collect progress from many go routines.

Since bar has more than the simple counter as state, a RWMutex seems like a good fit.

**Comment by gosuri** [comment]
Made Incr thread safe now :)

``` go
b := NewBar(10000)
runtime.GOMAXPROCS(runtime.NumCPU())
var wg sync.WaitGroup
for i := 0; i < 10000; i++ {
  wg.Add(1)
  go func() {
    defer wg.Done()
    b.Incr()
    time.Sleep(time.Millisecond * time.Duration(rand.Intn(10)))
  }()
}
wg.Wait()
```

**Comment by bep** [comment]
Great!

**Comment by bep** [comment]
OK, looking at the code: It doesn't help much JUST to add locks in `Incr` when all the other methods is reading and updating the same state.

**Comment by gosuri** [comment]
How about now?

**Comment by gosuri** [comment]
I've extended concurrency safety coverage to all read and write functions. Closing the issue, please let me know if you see anything missing. Thank you again.
